version: '3'
services:
  main:
    build: ./docker
    ports:
      - 5173:5173
    volumes:
      - node_modules:/app/node_modules
      - .:/app
    environment:
      - NODE_ENV=development
    command: "npm run dev -- --host"

volumes:
    node_modules:
